# Generated by Django 4.2.5 on 2023-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('employement_status', models.CharField(choices=[('S', 'Student'), ('P', 'Working Professional'), ('NA', 'Not Applicable')], max_length=15)),
                ('year_of_passing', models.IntegerField()),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
